default: &default
  adapter: postgresql
  encoding: unicode


development:
  <<: *default
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test


production:
  <<: *default
  database: portfolio_production
  username: portfolio
  password: <%= ENV['PORTFOLIO_DATABASE_PASSWORD'] %>
