# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adc7d8d0ddb0d64eb3fa196aa922cb6e75e72a30a44a43bd2e58dc4467319553eaa30c94e9d5fdc157e2eb24717f567291767b65f0ad3953ca6f7820ad349f7d

test:
  secret_key_base: 1dd0fd509beccabfd1396aa7934cc262d842f15954c0b168b77030552928d8659ec3af79eb2900092bdfcd0519937fa2778ebfa94e0206f94d68c69bd21b2ea4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
